version: '2'
services:
  konga:
    scale: 1
    start_on_create: false
  kong-migration:
    scale: 1
    start_on_create: false
  kong-database:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 9042
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      reinitializing_timeout: 60000
  kong:
    scale: 1
    start_on_create: false
